import type { EvidenceAnalysisRegistryEntry } from '../../types';

export const EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION = 'evidence_analysis_registry_v2' as const;

const freezeEntry = (entry: EvidenceAnalysisRegistryEntry): EvidenceAnalysisRegistryEntry =>
  Object.freeze({
    ...entry,
    accepted_source_kinds: Object.freeze([...entry.accepted_source_kinds]),
    accepted_row_scopes: entry.accepted_row_scopes ? Object.freeze([...entry.accepted_row_scopes]) : undefined,
    targets: Object.freeze(entry.targets.map(target => Object.freeze({ ...target }))),
    calculations: Object.freeze(entry.calculations.map(calculation => Object.freeze({
      ...calculation,
      output_fields: Object.freeze([...calculation.output_fields]),
    }))),
    forbidden_interpretations: Object.freeze([...entry.forbidden_interpretations]),
  });

const TABLE_KINDS = ['csv', 'tsv', 'xlsx'] as const;
const SHARED_FORBIDDEN = Object.freeze([
  'Do not infer culture, sentiment, or remediation from population metrics.',
  'Do not equate a missing field with a verified zero.',
  'Do not emit exact statistics, currency totals, or cell values to the model packet.',
  'Do not let a model recalculate or override deterministic outputs.',
  'Do not claim causality. causal_authority is always NONE.',
]);

export const EVIDENCE_ANALYSIS_REGISTRY_V2: readonly EvidenceAnalysisRegistryEntry[] = Object.freeze([
  freezeEntry({
    analyzer_id: 'crucial_item_coverage_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: ['text', 'pdf', 'csv', 'tsv', 'xlsx', 'md', 'docx'],
    accepted_row_scopes: ['acquired_corpus'],
    packet_representation: 'BANDED',
    packet_source_policy: 'PROFILE_ONLY',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: '*' }],
    calculations: [
      { calculation_id: 'expected_vs_found', formula: 'count found aliases / expected crucial items', output_fields: ['result.coverage.found', 'result.coverage.expected'], eligibility_rule: 'Acquired corpus text or headers exist.' },
      { calculation_id: 'coverage_band', formula: 'band found/expected percent', output_fields: ['result.coverage.coverage_band'], eligibility_rule: 'Expected items are registered for the criterion.' },
      { calculation_id: 'critical_coverage', formula: 'COMPLETE if no critical item is missing, else PARTIAL or MISSING', output_fields: ['result.coverage.critical_coverage', 'result.coverage.missing_items'], eligibility_rule: 'Critical flags are maintainer-owned.' },
    ],
    forbidden_interpretations: [
      ...SHARED_FORBIDDEN,
      'Do not treat NOT_FOUND as tested absence or as a lower maturity score.',
    ],
  }),
  freezeEntry({
    analyzer_id: 'trend_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    minimum_observations: 6,
    allowed_semantic_types: ['ratio', 'count', 'duration'],
    required_time_dimension: false,
    targets: [{ stream: 'maturity', criterion_id: 'C2' }],
    calculations: [
      { calculation_id: 'direction', formula: 'sign of first-to-last relative change, oriented by higher_is', output_fields: ['result.trend.direction'], eligibility_rule: 'Declared semantic series with n>=6.' },
      { calculation_id: 'magnitude_band', formula: 'band of |last-first|/|first|', output_fields: ['result.trend.magnitude_band'], eligibility_rule: 'Same series.' },
      { calculation_id: 'persistence', formula: 'aligned period-to-period deltas among last observations', output_fields: ['result.trend.persistence'], eligibility_rule: 'Same series.' },
    ],
    forbidden_interpretations: SHARED_FORBIDDEN,
  }),
  freezeEntry({
    analyzer_id: 'variation_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    minimum_observations: 6,
    allowed_semantic_types: ['ratio', 'count', 'duration'],
    targets: [{ stream: 'maturity', criterion_id: 'C2' }],
    calculations: [
      { calculation_id: 'variability', formula: 'CV = stdev/|mean|; LOW<0.10, MODERATE 0.10-0.30, HIGH>0.30', output_fields: ['result.variation.variability'], eligibility_rule: 'Same series as trend.' },
    ],
    forbidden_interpretations: SHARED_FORBIDDEN,
  }),
  freezeEntry({
    analyzer_id: 'concentration_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: 'A1' }],
    calculations: [
      { calculation_id: 'hhi_band', formula: 'HHI of segment weights; EVEN<0.15, MODERATE 0.15-0.25, HIGH>0.25', output_fields: ['result.concentration.concentration_band'], eligibility_rule: 'At least 3 allowlisted segments; never emit segment names.' },
    ],
    forbidden_interpretations: [
      ...SHARED_FORBIDDEN,
      'Do not emit team, account, or service names.',
    ],
  }),
  freezeEntry({
    analyzer_id: 'adoption_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: 'D2' }],
    calculations: [
      { calculation_id: 'practice_presence', formula: 'PRESENT if any eligible row is truthy', output_fields: ['result.adoption.practice_presence'], eligibility_rule: 'A registered adoption/enabled column is present.' },
      { calculation_id: 'adoption_band', formula: 'truthy rows / eligible rows, banded', output_fields: ['result.adoption.adoption_band'], eligibility_rule: 'Same column.' },
    ],
    forbidden_interpretations: SHARED_FORBIDDEN,
  }),
  freezeEntry({
    analyzer_id: 'process_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: 'C3' }],
    calculations: [
      { calculation_id: 'cadence', formula: 'median timestamp gap mapped to WEEKLY/MONTHLY/QUARTERLY/AD_HOC', output_fields: ['result.process.cadence'], eligibility_rule: 'Timestamps exist.' },
      { calculation_id: 'closure', formula: 'closed statuses / eligible rows, banded', output_fields: ['result.process.closure_band'], eligibility_rule: 'A status column exists.' },
      { calculation_id: 'aging', formula: 'median open-item age vs max timestamp in the table, banded', output_fields: ['result.process.aging_band'], eligibility_rule: 'Open items have timestamps.' },
    ],
    forbidden_interpretations: SHARED_FORBIDDEN,
  }),
  freezeEntry({
    analyzer_id: 'consistency_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: 'C2' }],
    calculations: [
      { calculation_id: 'declared_vs_observed_cadence', formula: 'compare corpus-declared cadence to observed timestamp gap band', output_fields: ['result.consistency.declared_cadence', 'result.consistency.observed_cadence'], eligibility_rule: 'A unique declared cadence and an observed process cadence exist for the same criterion.' },
      { calculation_id: 'agreement_state', formula: 'ALIGNED if declared equals observed, else DIVERGENT', output_fields: ['result.consistency.agreement_state', 'result.consistency.policy_execution_alignment'], eligibility_rule: 'Same pair.' },
    ],
    forbidden_interpretations: [
      ...SHARED_FORBIDDEN,
      'Do not treat cadence divergence as a maturity score.',
    ],
  }),
  freezeEntry({
    analyzer_id: 'exception_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    targets: [{ stream: 'maturity', criterion_id: 'A3' }],
    calculations: [
      { calculation_id: 'frequency', formula: 'registered exception rows / eligible rows, banded', output_fields: ['result.exception.frequency_band'], eligibility_rule: 'A registered exception/override/alert column is present. No open-ended spike hunting.' },
      { calculation_id: 'recurrence', formula: 'same entity key flagged more than once', output_fields: ['result.exception.recurrence'], eligibility_rule: 'A stable entity key exists.' },
    ],
    forbidden_interpretations: [
      ...SHARED_FORBIDDEN,
      'Do not discover anomalies on raw cost series.',
    ],
  }),
  freezeEntry({
    analyzer_id: 'association_v1',
    analyzer_version: '1.0.0',
    registry_version: EVIDENCE_ANALYSIS_REGISTRY_V2_VERSION,
    approval_status: 'APPROVED',
    approved_for_model_packet: true,
    accepted_source_kinds: TABLE_KINDS,
    accepted_row_scopes: ['full_table'],
    packet_representation: 'BANDED',
    packet_source_policy: 'WITHHOLD_CELL_VALUES',
    exact_result_retention: 'LOCAL_ONLY',
    causal_authority: 'NONE',
    minimum_observations: 6,
    targets: [{ stream: 'maturity', criterion_id: 'C2' }],
    calculations: [
      { calculation_id: 'association_direction', formula: 'sign of Pearson r on a closed pair, or NONE', output_fields: ['result.association.association_direction'], eligibility_rule: 'Both registered columns exist; n>=6; neither series is constant.' },
      { calculation_id: 'association_strength', formula: 'band |r|: <0.3 none, <0.6 weak, <0.8 moderate, else strong', output_fields: ['result.association.association_strength'], eligibility_rule: 'Same pair. Exact r is LOCAL_ONLY.' },
    ],
    forbidden_interpretations: [
      ...SHARED_FORBIDDEN,
      'Do not explore unregistered column pairs.',
      'Do not claim that one series causes the other.',
    ],
  }),
]);

