BEGIN;
CREATE TABLE IF NOT EXISTS run_shadow_telemetry (
  run_id uuid PRIMARY KEY REFERENCES runs(run_id) ON DELETE CASCADE,
  schema_version text NOT NULL CHECK (schema_version = 'shadow_telemetry_v1'),
  retrieval_policy_version text NOT NULL CHECK (retrieval_policy_version = 'bounded_retrieval_policy_v1'),
  derived_evidence_schema_version text NOT NULL CHECK (derived_evidence_schema_version = 'derived_analytical_evidence_v1'),
  analyzer_version text NOT NULL CHECK (analyzer_version = 'tagging_allocation_v1@1.0.0'),
  scale_registry_version text NOT NULL CHECK (scale_registry_version = 'data_signal_registry_v1'),
  retrieval_domain_count smallint NOT NULL CHECK (retrieval_domain_count BETWEEN 0 AND 10000),
  retrieval_triggered_domain_count smallint NOT NULL CHECK (retrieval_triggered_domain_count BETWEEN 0 AND retrieval_domain_count),
  retrieval_pass_1_count smallint NOT NULL CHECK (retrieval_pass_1_count = retrieval_triggered_domain_count),
  retrieval_pass_2_count smallint NOT NULL CHECK (retrieval_pass_2_count BETWEEN 0 AND retrieval_pass_1_count),
  retrieval_selected_candidate_count integer NOT NULL CHECK (retrieval_selected_candidate_count BETWEEN 0 AND 10000),
  retrieval_average_gain_points smallint NOT NULL CHECK (retrieval_average_gain_points BETWEEN 0 AND 100),
  retrieval_max_gain_points smallint NOT NULL CHECK (retrieval_max_gain_points BETWEEN 0 AND 100),
  stop_sufficient_baseline_count smallint NOT NULL CHECK (stop_sufficient_baseline_count BETWEEN 0 AND 10000),
  stop_minimum_gain_not_met_count smallint NOT NULL CHECK (stop_minimum_gain_not_met_count BETWEEN 0 AND 10000),
  stop_no_new_candidates_count smallint NOT NULL CHECK (stop_no_new_candidates_count BETWEEN 0 AND 10000),
  stop_max_passes_reached_count smallint NOT NULL CHECK (stop_max_passes_reached_count BETWEEN 0 AND 10000),
  derived_evidence_count smallint NOT NULL CHECK (derived_evidence_count BETWEEN 0 AND 10000),
  derived_observed_count smallint NOT NULL CHECK (derived_observed_count BETWEEN 0 AND derived_evidence_count),
  derived_insufficient_signal_count smallint NOT NULL CHECK (derived_insufficient_signal_count BETWEEN 0 AND derived_evidence_count),
  derived_full_table_count smallint NOT NULL CHECK (derived_full_table_count BETWEEN 0 AND derived_evidence_count),
  derived_bounded_prefix_count smallint NOT NULL CHECK (derived_bounded_prefix_count BETWEEN 0 AND derived_evidence_count),
  scale_total_object_count smallint NOT NULL CHECK (scale_total_object_count BETWEEN 0 AND 10000),
  scale_analyzer_available_count smallint NOT NULL CHECK (scale_analyzer_available_count BETWEEN 0 AND scale_total_object_count),
  scale_unsupported_count smallint NOT NULL CHECK (scale_unsupported_count BETWEEN 0 AND scale_total_object_count),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  metadata_expires_at timestamptz NOT NULL DEFAULT (clock_timestamp()+interval '90 days'),
  CHECK (stop_sufficient_baseline_count + stop_minimum_gain_not_met_count + stop_no_new_candidates_count + stop_max_passes_reached_count = retrieval_domain_count),
  CHECK (derived_observed_count + derived_insufficient_signal_count = derived_evidence_count),
  CHECK (derived_full_table_count + derived_bounded_prefix_count = derived_evidence_count),
  CHECK (scale_analyzer_available_count + scale_unsupported_count = scale_total_object_count)
);
COMMIT;
