import crypto from 'node:crypto';
import { authorizeDestination,evaluatePacketBinding,inspectOutput,packetRuntimeDiagnostics,parseApprovedPacketBody,validateGovernedOutput } from './governance.js';
import { invokeProvider } from './providerInvocation.js';
import { LIFETIMES_MS } from './controlPlanePolicy.js';
import { safeWorkerErrorCode,workerOperationalLog } from './workerOperationalLog.js';
import { outputContractDiagnostics,validateOutputContractText } from './outputContracts.js';

const fallbackCodes=new Set(['PROVIDER_NOT_CONFIGURED','UPSTREAM_HTTP_ERROR','INCOMPLETE_RESPONSE','OUTPUT_INSPECTION_REJECTED','INVALID_OUTPUT_CONTRACT']);
// Six domain analyses share a bounded worker. A healthy fallback can therefore
// wait behind a full wave of long-running model calls; one minute is shorter
// than observed provider latency and incorrectly exhausts the fallback chain.
const MAX_QUEUE_WAIT_MS=8*60_000;
const usageAllowlist=u=>({input_tokens:Number.isSafeInteger(u?.input_tokens)?u.input_tokens:undefined,output_tokens:Number.isSafeInteger(u?.output_tokens)?u.output_tokens:undefined,reasoning_tokens:Number.isSafeInteger(u?.reasoning_tokens)?u.reasoning_tokens:undefined});
const terminationReason=e=>['MAX_OUTPUT_TOKENS','CONTEXT_WINDOW_EXCEEDED','PROVIDER_INCOMPLETE','PROVIDER_REFUSAL'].includes(e?.terminationReason)?e.terminationReason:undefined;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const preSendFallbackCodes=new Set(['PACKET_UNAVAILABLE','DEPENDENCY_UNAVAILABLE']);

export class ExecutionWorker{
  constructor({repository,redis,invoke=invokeProvider,providerConfigured=p=>p==='openai'?Boolean(process.env.GPT_API_KEY||process.env.OPENAI_API_KEY):p==='xai'?Boolean(process.env.XAI_API_KEY):p==='anthropic'?Boolean(process.env.ANTHROPIC_API_KEY):false,owner=crypto.randomUUID(),pollMs=500,heartbeatMs=10_000,leaseSeconds=60,maxConcurrency=4}){Object.assign(this,{repository,redis,invoke,providerConfigured,owner,pollMs,heartbeatMs,leaseSeconds,maxConcurrency});this.stopped=true;this.active=new Set();}
  async process(attemptId){
    const leased=await this.repository.claimAttempt(attemptId,this.owner,this.leaseSeconds);if(!leased)return;
    const a=await this.repository.getAttempt(attemptId);if(!a)return;
    const processingStarted=Date.now();workerOperationalLog('info','execution_attempt_claimed',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,queue_age_ms:processingStarted-new Date(a.created_at).getTime()});
    const stopBeforeSend=async code=>{const fallbackAllowed=preSendFallbackCodes.has(code);const next=fallbackAllowed?'fallback_allowed':'cancelled';const changed=await this.repository.transitionAttempt(attemptId,a.state,next,{outcomeCode:code});if(changed)workerOperationalLog('warn','execution_attempt_cancelled',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,outcome_code:code,fallback_allowed:fallbackAllowed,duration_ms:Date.now()-processingStarted});return changed;};
    if(a.run_state!=='active'||Date.now()>=new Date(a.effective_expires_at).getTime())return stopBeforeSend('RUN_INACTIVE');
    if(Date.now()>=new Date(a.packet_expires_at).getTime())return stopBeforeSend('PACKET_UNAVAILABLE');
    const canonicalBody=a.canonical_body;if(!canonicalBody)return stopBeforeSend('PACKET_UNAVAILABLE');let packet;try{packet=parseApprovedPacketBody(canonicalBody,a.packet_hash);}catch(error){return stopBeforeSend(error?.code||'DEPENDENCY_UNAVAILABLE');}
    const packetBinding=evaluatePacketBinding(packet,{packetId:a.packet_id,packetHash:a.packet_hash,runId:a.run_id,provider:a.provider,model:a.model,stage:a.stage},canonicalBody);
    if(packetBinding.code){workerOperationalLog('warn','execution_packet_binding_mismatch',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,outcome_code:packetBinding.code,...packetBinding.matches,...packetRuntimeDiagnostics(packet,canonicalBody)});return stopBeforeSend(packetBinding.code);}
    workerOperationalLog('info','execution_packet_worker_validated',{run_id:a.run_id,attempt_id:attemptId,packet_id:a.packet_id,stage:a.stage,provider:a.provider,model:a.model,...packetRuntimeDiagnostics(packet,canonicalBody)});
    try{authorizeDestination(a.stage,a.provider,a.model,packet.settings);}catch{return stopBeforeSend('POLICY_VALIDATION_FAILED');}
    if(a.state==='queued'&&Date.now()-new Date(a.created_at).getTime()>MAX_QUEUE_WAIT_MS)return this.repository.transitionAttempt(attemptId,'queued','fallback_allowed',{outcomeCode:'QUEUE_WAIT_EXCEEDED'});
    let lease;try{lease=Number(await this.redis.setLease(a.run_id,attemptId,leased.lease_token,a.absolute_deadline_at,(this.leaseSeconds+5)*1000));}catch{return stopBeforeSend('DEPENDENCY_UNAVAILABLE');}
    if(lease===3)return this.repository.transitionAttempt(attemptId,a.state,'outcome_unknown',{outcomeCode:'DISPATCH_AMBIGUITY'});
    if(lease!==1)return stopBeforeSend('RUN_INACTIVE');
    if(a.state==='queued'&&!await this.repository.transitionAttempt(attemptId,'queued','dispatch_intent'))return;if(!this.providerConfigured(a.provider)){await this.repository.transitionAttempt(attemptId,'dispatch_intent','fallback_allowed',{outcomeCode:'PROVIDER_NOT_CONFIGURED'});return;}
    const auth=await this.redis.authorizeSend({runId:a.run_id,attemptId,token:leased.lease_token,deadline:a.absolute_deadline_at,ttlMs:LIFETIMES_MS.packet});
    if(auth!==1){await this.repository.transitionAttempt(attemptId,'dispatch_intent','outcome_unknown',{outcomeCode:'DISPATCH_AMBIGUITY'});return;}
    if(!await this.repository.authorizeAttempt(attemptId,this.owner,leased.lease_token)){await this.repository.transitionAttempt(attemptId,'dispatch_intent','outcome_unknown',{outcomeCode:'DISPATCH_AMBIGUITY'});return;}
    const controller=new AbortController();let fenceLost=false,running=true,stopHeartbeat;const stopped=new Promise(resolve=>{stopHeartbeat=resolve;});
    const heartbeat=async()=>{while(running){await Promise.race([sleep(this.heartbeatMs),stopped]);if(!running)return;try{const [db,cache]=await Promise.all([this.repository.renewAttemptLease(attemptId,this.owner,leased.lease_token,this.leaseSeconds),this.redis.renewLease(a.run_id,attemptId,leased.lease_token,(this.leaseSeconds+5)*1000)]);if(!db||!cache){fenceLost=true;controller.abort();return;}}catch{fenceLost=true;controller.abort();return;}}};
    const heartbeatTask=heartbeat();
    let responseText='';
    try{const {text,usage}=await this.invoke(packet,{signal:controller.signal});responseText=text;if(fenceLost)throw Object.assign(new Error(),{code:'FENCE_LOST'});if(packet.output_contract)validateOutputContractText(packet.output_contract,text);const output=inspectOutput(text,packet);validateGovernedOutput(output,{source_packet_id:a.packet_id,source_packet_hash:a.packet_hash,run_id:a.run_id,stage:a.stage,provider:a.provider,model:a.model});const safeUsage=usageAllowlist(usage);const stored=await this.redis.setResult({runId:a.run_id,id:attemptId,value:JSON.stringify({status:'done',output,usage:safeUsage}),deadline:a.absolute_deadline_at,ttlMs:LIFETIMES_MS.resultRecovery});if(stored!==1&&stored!==2){await this.repository.transitionAttempt(attemptId,'send_authorized','result_unavailable',{outcomeCode:'RESULT_STORAGE_FAILED'});workerOperationalLog('error','execution_attempt_failed',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,outcome_code:'RESULT_STORAGE_FAILED',duration_ms:Date.now()-processingStarted});return;}await this.repository.transitionAttempt(attemptId,'send_authorized','succeeded',{inputTokens:safeUsage.input_tokens,outputTokens:safeUsage.output_tokens});workerOperationalLog('info','execution_attempt_succeeded',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,duration_ms:Date.now()-processingStarted});}
    catch(error){const code=fenceLost||error?.name==='AbortError'?'OUTCOME_UNKNOWN':error?.code;if(code==='INVALID_OUTPUT_CONTRACT')workerOperationalLog('warn','execution_output_rejected',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,...outputContractDiagnostics(responseText,error)});if(fallbackCodes.has(code))await this.repository.transitionAttempt(attemptId,'send_authorized','fallback_allowed',{outcomeCode:code});else await this.repository.transitionAttempt(attemptId,'send_authorized','outcome_unknown',{outcomeCode:'OUTCOME_UNKNOWN'});workerOperationalLog('warn','execution_attempt_failed',{run_id:a.run_id,attempt_id:attemptId,stage:a.stage,provider:a.provider,model:a.model,outcome_code:fallbackCodes.has(code)?code:'OUTCOME_UNKNOWN',termination_reason:terminationReason(error),provider_http_status:error?.providerHttpStatus,provider_error_code:error?.providerErrorCode,provider_request_id:error?.providerRequestId,duration_ms:Date.now()-processingStarted});}
    finally{running=false;stopHeartbeat();await heartbeatTask;}
  }
  start(){if(!this.stopped)return;this.stopped=false;workerOperationalLog('info','execution_worker_started');this.loopPromise=this.loop();}
  async loop(){let last='0-0';while(!this.stopped){try{const rows=await this.redis.readAttempts(last,this.pollMs);for(const stream of rows||[])for(const message of stream.messages||[]){last=message.id;while(!this.stopped&&this.active.size>=this.maxConcurrency)await Promise.race(this.active);if(this.stopped)break;const job=this.process(message.message.attempt_id).catch(error=>workerOperationalLog('error','execution_attempt_processing_error',{attempt_id:message.message.attempt_id,error_code:safeWorkerErrorCode(error)})).finally(()=>this.active.delete(job));this.active.add(job);}}catch(error){if(!this.stopped){workerOperationalLog('error','execution_worker_loop_error',{error_code:safeWorkerErrorCode(error)});await sleep(this.pollMs);}}}}
  async stop(){this.stopped=true;await this.loopPromise;await Promise.allSettled([...this.active]);}
}
export class OutboxPublisher{constructor({repository,redis,owner=crypto.randomUUID(),intervalMs=500}){Object.assign(this,{repository,redis,owner,intervalMs});this.stopped=true;}start(){if(!this.stopped)return;this.stopped=false;workerOperationalLog('info','outbox_publisher_started');this.loopPromise=this.loop();}async loop(){while(!this.stopped){try{await this.tick();}catch(error){workerOperationalLog('error','outbox_publisher_error',{error_code:safeWorkerErrorCode(error)});}if(!this.stopped)await sleep(this.intervalMs);}}async tick(){for(const row of await this.repository.claimPendingOutbox(this.owner)){await this.redis.notifyAttempt(row.attempt_id);if(await this.repository.markPublished(row.outbox_id,this.owner))workerOperationalLog('info','outbox_attempt_published',{run_id:row.run_id,attempt_id:row.attempt_id});}}async stop(){this.stopped=true;await this.loopPromise;}}

export class AttemptReconciler{
  constructor({repository,redis,intervalMs=10_000}){Object.assign(this,{repository,redis,intervalMs});this.stopped=true;}
  async tick(){await this.repository.reconcileStale();for(const a of await this.repository.listReconciliationCandidates()){const raw=await this.redis.getResult(a.run_id,a.attempt_id);if(raw){try{const r=JSON.parse(raw);if(r.status!=='done')throw new Error();validateGovernedOutput(r.output,{source_packet_id:a.packet_id,source_packet_hash:a.packet_hash,run_id:a.run_id,stage:a.stage,provider:a.provider,model:a.model});const usage=usageAllowlist(r.usage);await this.repository.recoverSucceeded(a.attempt_id,{inputTokens:usage.input_tokens,outputTokens:usage.output_tokens});continue;}catch{}}
      const marker=await this.redis.getSendMarker(a.run_id,a.attempt_id);if(a.state==='outcome_unknown')continue;if(a.state==='dispatch_intent'&&!marker){await this.redis.notifyAttempt(a.attempt_id);continue;}await this.repository.transitionAttempt(a.attempt_id,a.state,'outcome_unknown',{outcomeCode:'DISPATCH_AMBIGUITY'});
    }}
  start(){if(!this.stopped)return;this.stopped=false;workerOperationalLog('info','attempt_reconciler_started');this.loopPromise=this.loop();}async loop(){while(!this.stopped){try{await this.tick();}catch(error){workerOperationalLog('error','attempt_reconciler_error',{error_code:safeWorkerErrorCode(error)});}if(!this.stopped)await sleep(this.intervalMs);}}async stop(){this.stopped=true;await this.loopPromise;}
}
