import { requireSession } from '../lib/auth.js';
import { getInfrastructure } from '../lib/infrastructure.js';
import { safeErrorCode,safeErrorStatus } from '../lib/safeErrors.js';
import { RunLifecycleService } from '../lib/runLifecycleService.js';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const QUALITY_KEYS=['schema_version','formula_version','extraction_completeness','evidence_coverage','evidence_density','provenance_integrity','kb_completeness','evidence_packet_status','knowledge_packet_status','acquisition_status','security_status','extraction_incomplete_count','weak_source_packet_count','kb_blocking_count','unresolved_provenance_count'];
const SHADOW_KEYS=['schema_version','retrieval_policy_version','derived_evidence_schema_version','analyzer_version','scale_registry_version','retrieval_domain_count','retrieval_triggered_domain_count','retrieval_pass_1_count','retrieval_pass_2_count','retrieval_selected_candidate_count','retrieval_average_gain_points','retrieval_max_gain_points','stop_sufficient_baseline_count','stop_minimum_gain_not_met_count','stop_no_new_candidates_count','stop_max_passes_reached_count','derived_evidence_count','derived_observed_count','derived_insufficient_signal_count','derived_full_table_count','derived_bounded_prefix_count','scale_total_object_count','scale_analyzer_available_count','scale_unsupported_count'];
export function validQualitySnapshot(q){if(!q||typeof q!=='object'||Array.isArray(q)||Object.keys(q).sort().join('|')!==[...QUALITY_KEYS].sort().join('|'))return false;const percentages=['extraction_completeness','evidence_coverage','evidence_density','provenance_integrity','kb_completeness'];const counts=['extraction_incomplete_count','weak_source_packet_count','kb_blocking_count','unresolved_provenance_count'];return q.schema_version==='acquisition_quality_snapshot_v1'&&q.formula_version==='acquisition_quality_formula_v1'&&percentages.every(k=>Number.isInteger(q[k])&&q[k]>=0&&q[k]<=100)&&counts.every(k=>Number.isInteger(q[k])&&q[k]>=0&&q[k]<=10000)&&['READY','NOT_READY'].includes(q.evidence_packet_status)&&['READY','NOT_READY'].includes(q.knowledge_packet_status)&&['READY','NOT_READY'].includes(q.acquisition_status)&&['PASS','WARN','BLOCK'].includes(q.security_status);}
export function validShadowTelemetry(t){if(!t||typeof t!=='object'||Array.isArray(t)||Object.keys(t).sort().join('|')!==[...SHADOW_KEYS].sort().join('|'))return false;const percentages=['retrieval_average_gain_points','retrieval_max_gain_points'];const counts=SHADOW_KEYS.filter(k=>k.endsWith('_count'));if(t.schema_version!=='shadow_telemetry_v1'||t.retrieval_policy_version!=='bounded_retrieval_policy_v1'||t.derived_evidence_schema_version!=='derived_analytical_evidence_v1'||t.analyzer_version!=='tagging_allocation_v1@1.3.0'||!['data_signal_registry_v1','data_signal_registry_v2'].includes(t.scale_registry_version)||!percentages.every(k=>Number.isInteger(t[k])&&t[k]>=0&&t[k]<=100)||!counts.every(k=>Number.isInteger(t[k])&&t[k]>=0&&t[k]<=10000))return false;return t.retrieval_triggered_domain_count<=t.retrieval_domain_count&&t.retrieval_pass_2_count<=t.retrieval_pass_1_count&&t.retrieval_triggered_domain_count===t.retrieval_pass_1_count&&t.stop_sufficient_baseline_count+t.stop_minimum_gain_not_met_count+t.stop_no_new_candidates_count+t.stop_max_passes_reached_count===t.retrieval_domain_count&&t.derived_observed_count+t.derived_insufficient_signal_count===t.derived_evidence_count&&t.derived_full_table_count+t.derived_bounded_prefix_count===t.derived_evidence_count&&t.scale_analyzer_available_count+t.scale_unsupported_count===t.scale_total_object_count;}
export function createRunHandler(repository,redis){const lifecycle=redis?new RunLifecycleService({repository,redis}):null;return async function(req,res){
  if(!requireSession(req))return res.status(401).json({error:'AUTHENTICATION_REQUIRED'});
  if(!['GET','POST','DELETE'].includes(req.method))return res.status(405).json({error:'METHOD_NOT_ALLOWED'});
  try {
    const body=req.body||{}; const action=req.method==='GET'?'status':req.method==='DELETE'?'delete':body.action;
    let result;
    if(action==='create'&&req.method==='POST')result=await repository.createRun();
    else { const id=body.run_id||req.query?.run_id; if(typeof id!=='string'||!UUID.test(id))return res.status(400).json({error:'INVALID_REQUEST'});
      if(action==='status')result=await repository.getRun(id);
      else if(action==='suspend'){const failureCode=typeof body.failure_code==='string'&&/^[A-Z0-9_]{1,64}$/.test(body.failure_code)?body.failure_code:'PIPELINE_FAILED';result=await repository.markRunRecoverable(id,failureCode);}
      else if(action==='resume')result=await repository.resumeRun(id);
      else if(action==='ready'){if(!validQualitySnapshot(body.quality)||!validShadowTelemetry(body.shadow_telemetry))return res.status(400).json({error:'INVALID_REQUEST'});result=await (lifecycle?lifecycle.readyWithQuality(id,body.quality,body.shadow_telemetry):repository.readyRunWithQuality(id,body.quality,body.shadow_telemetry));}
      else if(action==='acknowledge')result=await (lifecycle?lifecycle.acknowledgeDelivery(id):repository.acknowledgeDelivery(id));
      else if(action==='complete'){if(!validQualitySnapshot(body.quality)||!validShadowTelemetry(body.shadow_telemetry))return res.status(400).json({error:'INVALID_REQUEST'});result=await (lifecycle?lifecycle.completeWithQuality(id,body.quality,body.shadow_telemetry):repository.completeRunWithQuality(id,body.quality,body.shadow_telemetry));}
      else if(action==='fail'){const failureCode=typeof body.failure_code==='string'&&/^[A-Z0-9_]{1,64}$/.test(body.failure_code)?body.failure_code:'PIPELINE_FAILED';result=await (lifecycle?lifecycle.transition(id,'failed',failureCode):repository.terminalRun(id,'failed',failureCode));}
      else if(action==='delete')result=await (lifecycle?lifecycle.transition(id,'deletion_requested'):repository.terminalRun(id,'deletion_requested'));
      else return res.status(400).json({error:'INVALID_REQUEST'});
    }
    if(!result)return res.status(404).json({error:'RUN_NOT_FOUND'});
    return res.status(action==='create'?201:200).json(result);
  } catch(error){const code=safeErrorCode(error);return res.status(safeErrorStatus(code)).json({error:code});}
};}
export default async function handler(req,res){try{const {repository,redis}=getInfrastructure();return await createRunHandler(repository,redis)(req,res);}catch{return res.status(503).json({error:'VERCEL_GOVERNED_DISPATCH_UNSUPPORTED'});}}
